version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'opentable'
      MYSQL_USER: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  main:
    image: ezli/ot-right-reservations_main:booking
    depends_on:
      - 'db'
    ports: 
      - '3003:3003'